import type { Provider } from "@/lib/types";

export const DEMO_PROVIDERS: Provider[] = [
  {
    id: "demo-youssef",
    fullName: "يوسف العلوي",
    profession: "كهربائي",
    city: "الدار البيضاء",
    bio: "خدمة كهرباء المنازل والمحلات، إصلاح الأعطاب وتركيب الإنارة. كنخدم بالمواعيد وبجودة مضمونة.",
    yearsExperience: 8,
    travelsToClient: true,
    availability: [
      { weekday: 1, start: "18:00", end: "21:00" },
      { weekday: 2, start: "18:00", end: "21:00" },
      { weekday: 3, start: "14:00", end: "18:00" },
      { weekday: 4, start: "18:00", end: "21:00" },
      { weekday: 6, start: "10:00", end: "15:00" },
    ],
    rating: 4.9,
    reviewCount: 38,
    color: "mint",
  },
  {
    id: "demo-salma",
    fullName: "سلمى بناني",
    profession: "تنظيف المنازل",
    city: "الرباط",
    bio: "تنظيف عميق ومنتظم للمنازل والمكاتب. كنجيب معايا أدوات ومواد تنظيف صديقة للبيئة.",
    yearsExperience: 5,
    travelsToClient: true,
    availability: [
      { weekday: 1, start: "09:00", end: "13:00" },
      { weekday: 2, start: "09:00", end: "13:00" },
      { weekday: 3, start: "09:00", end: "13:00" },
      { weekday: 4, start: "09:00", end: "13:00" },
      { weekday: 5, start: "09:00", end: "13:00" },
    ],
    rating: 5.0,
    reviewCount: 24,
    color: "peach",
  },
  {
    id: "demo-hamza",
    fullName: "حمزة المرابط",
    profession: "سباك",
    city: "مراكش",
    bio: "إصلاح التسريبات، تركيب السخانات والصنابير، وصيانة شبكات الماء للمنازل.",
    yearsExperience: 11,
    travelsToClient: true,
    availability: [
      { weekday: 1, start: "10:00", end: "17:00" },
      { weekday: 2, start: "10:00", end: "17:00" },
      { weekday: 4, start: "10:00", end: "17:00" },
      { weekday: 5, start: "10:00", end: "17:00" },
      { weekday: 6, start: "09:00", end: "13:00" },
    ],
    rating: 4.8,
    reviewCount: 51,
    color: "blue",
  },
  {
    id: "demo-iman",
    fullName: "إيمان الإدريسي",
    profession: "مصممة ديكور",
    city: "طنجة",
    bio: "تصميم داخلي عملي وبسيط للمنازل والمشاريع الصغيرة، من الفكرة حتى اختيار الألوان والأثاث.",
    yearsExperience: 6,
    travelsToClient: false,
    availability: [
      { weekday: 2, start: "11:00", end: "18:00" },
      { weekday: 3, start: "11:00", end: "18:00" },
      { weekday: 5, start: "12:00", end: "19:00" },
      { weekday: 6, start: "10:00", end: "16:00" },
    ],
    rating: 4.9,
    reviewCount: 19,
    color: "lavender",
  },
  {
    id: "demo-rida",
    fullName: "رضا التازي",
    profession: "نجار",
    city: "فاس",
    bio: "صناعة وإصلاح الأبواب والخزائن والأثاث الخشبي حسب القياس، مع معاينة أولية مجانية.",
    yearsExperience: 9,
    travelsToClient: true,
    availability: [
      { weekday: 1, start: "08:00", end: "15:00" },
      { weekday: 3, start: "08:00", end: "15:00" },
      { weekday: 4, start: "08:00", end: "15:00" },
      { weekday: 5, start: "08:00", end: "15:00" },
      { weekday: 6, start: "08:00", end: "12:00" },
    ],
    rating: 4.7,
    reviewCount: 31,
    color: "sand",
  },
  {
    id: "demo-nadia",
    fullName: "نادية أمين",
    profession: "حلاقة وتجميل",
    city: "أكادير",
    bio: "تصفيف الشعر والمكياج للمناسبات. متاحة كذلك لخدمة منزلية بالحجز المسبق.",
    yearsExperience: 7,
    travelsToClient: true,
    availability: [
      { weekday: 1, start: "13:00", end: "20:00" },
      { weekday: 3, start: "13:00", end: "20:00" },
      { weekday: 4, start: "13:00", end: "20:00" },
      { weekday: 6, start: "10:00", end: "18:00" },
      { weekday: 7, start: "10:00", end: "14:00" },
    ],
    rating: 4.9,
    reviewCount: 42,
    color: "rose",
  },
];

export const PROFESSIONS = [
  "كهربائي",
  "سباك",
  "نجار",
  "تنظيف المنازل",
  "مصممة ديكور",
  "حلاقة وتجميل",
  "صباغ",
  "تقني تكييف",
  "مصور",
  "مساعد منزلي",
];

export const CITIES = [
  "الدار البيضاء",
  "الرباط",
  "مراكش",
  "فاس",
  "طنجة",
  "أكادير",
  "مكناس",
  "وجدة",
];
